version: "3.2"

services:
  server:
    build: ./server
    ports:
      - 3001:3000
    container_name: dev-server
    volumes:
      - ./server/src:/app/src
      - ./server/data:/app/assets
    command: ["npm", "run", "dev"]

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 30011:30011
    container_name: dev-client
    volumes:
      - ./client/src:/app/src
    environment:
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
