apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: joonashak/dwk-ping-pong
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ping-pong-db-pwd
            - name: PGHOST
              value: ping-pong-db-svc
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: postgres
