apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: project-server-ing
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        backend:
          serviceName: ping-pong-svc
          servicePort: 2345
