apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-db
  namespace: main
spec:
  serviceName: ping-pong-svc
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: db
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ping-pong-db-pwd
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: main
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
